import { jsPDF } from 'jspdf';
import 'jspdf-autotable';
import { Message, ChatSession } from '../types';

export const exportToPDF = (title: string, content: string, filename: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header
  doc.setFontSize(22);
  doc.setTextColor(51, 87, 101); // brand-primary
  doc.text('DEFENDER AI', pageWidth / 2, 20, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text('OFFICIAL LEGAL CASE BRIEF', pageWidth / 2, 28, { align: 'center' });
  
  doc.setDrawColor(51, 87, 101);
  doc.setLineWidth(0.5);
  doc.line(20, 35, pageWidth - 20, 35);
  
  // Title
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(title.toUpperCase(), 20, 50);
  
  // Date
  doc.setFontSize(10);
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${new Date().toLocaleString()}`, 20, 58);
  
  // Content
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  const splitText = doc.splitTextToSize(content, pageWidth - 40);
  doc.text(splitText, 20, 75);
  
  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text('Disclaimer: This document is generated by an AI assistant and is for informational purposes only. Consult a qualified legal professional for official legal advice.', pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: 'center' });
  }
  
  doc.save(`${filename}.pdf`);
};

export const generateCaseBrief = (session: ChatSession, messages: Message[]) => {
  let content = `Case Title: ${session.title}\n\n`;
  
  // Group by role
  messages.forEach((msg, index) => {
    const role = msg.role === 'user' ? 'CLIENT' : 'DEFENDER AI';
    content += `[${role}]:\n${msg.content}\n\n`;
    
    if (msg.role === 'assistant' && index === messages.length - 1) {
      content += `\n--- SUMMARY OF LEGAL ADVICE ---\n`;
      content += `The above consultation provides a preliminary analysis of the legal issue based on the Indian Penal Code (IPC), Code of Criminal Procedure (CrPC), and relevant civil laws. The client is advised to maintain all evidence and seek formal legal representation if litigation is required.`;
    }
  });
  
  exportToPDF(session.title, content, `Case_Brief_${session.id.substring(0, 8)}`);
};

export const generateLegalNotice = (content: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Formal Legal Notice Header
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('LEGAL NOTICE', pageWidth / 2, 30, { align: 'center' });
  
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 45);
  
  // Formal body
  const splitText = doc.splitTextToSize(content, pageWidth - 40);
  doc.text(splitText, 20, 60);
  
  // Signature line
  const lastY = 60 + (splitText.length * 7);
  doc.text('__________________________', 20, lastY + 20);
  doc.text('(Signature of the Sender)', 20, lastY + 27);
  
  doc.save(`Legal_Notice_${new Date().getTime()}.pdf`);
};

export const generateEvidenceBundle = (files: { name: string; url: string; type: string }[]) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  doc.setFontSize(20);
  doc.text('EVIDENCE BUNDLE', pageWidth / 2, 30, { align: 'center' });
  
  doc.setFontSize(10);
  doc.text(`Total Items: ${files.length}`, 20, 45);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 20, 52);
  
  const tableData = files.map((f, i) => [i + 1, f.name, f.type, 'Verified by AI']);
  
  (doc as any).autoTable({
    startY: 60,
    head: [['#', 'File Name', 'Type', 'Status']],
    body: tableData,
    theme: 'grid',
    headStyles: { fillColor: [51, 87, 101] }
  });
  
  doc.save(`Evidence_Bundle_${new Date().getTime()}.pdf`);
};

export const generateCalendarEvent = (title: string, dateStr: string) => {
  const date = new Date(dateStr);
  if (isNaN(date.getTime())) {
    alert('Invalid date format. Please provide a valid date.');
    return;
  }
  
  const start = date.toISOString().replace(/-|:|\.\d+/g, '');
  const end = new Date(date.getTime() + 60 * 60 * 1000).toISOString().replace(/-|:|\.\d+/g, '');
  
  const icsContent = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'BEGIN:VEVENT',
    `SUMMARY:${title}`,
    `DTSTART:${start}`,
    `DTEND:${end}`,
    'DESCRIPTION:Legal deadline generated by Defender AI',
    'END:VEVENT',
    'END:VCALENDAR'
  ].join('\n');
  
  const blob = new Blob([icsContent], { type: 'text/calendar;charset=utf-8' });
  const link = document.createElement('a');
  link.href = window.URL.createObjectURL(blob);
  link.setAttribute('download', 'legal_deadline.ics');
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
